### ISSUE TITLE
webex_card.js feature modules fails on Glitch as it uses the PUBLIC_ADDRESS env variable,

### ISSUE THREAD

**Issue by dstaudt** [CiscoDevNet/botkit-template#13]

**Comment by dstaudt** [comment]
Should be fixed by https://github.com/CiscoDevNet/botkit-template/commit/0beda201de3c7994fed04f71dfa8e002bd50111b

Note this commit also changes the env variable name to PUBLIC_URL (as well as ACCESS_TOKEN to WEBEX_ACCESS_TOKEN)

**Comment by ObjectIsAdvantag** [comment]
I believe it's now fully fixed thanks to #14  
successfully tested the card example
closing
