### ISSUE TITLE
add a "how to debug" section

### ISSUE THREAD

**Issue by ObjectIsAdvantag** [CiscoDevNet/botkit-template#15]
I got the feedback of someone having difficulties debug from VSCode
We should add a section covering this

- do NOT use .env when debugging from VSCode
- provide an example of .vscode/launch.json file ready to fill with the developer secret

**Comment by ObjectIsAdvantag** [comment]
Extra feedback

> But from what I can tell, the use of .env when debugging isn't a problem. The error has nothing to do with reading the environment (webex sdk initializes just fine), but rather that that botkit doesn't load the modules properly. I HAVE tried setting the environment in launch.json as you suggested.

**Comment by dstaudt** [comment]
Clarify the ask here?  What is the issue and the proposed fix..?

There is a need to modify the .env usage here a bit, in that '.env.example' should be the file in the repo, with instructions to rename to '.env' for running.  (With .env in .gitignore to prevent version controlling credentials.)

I would like to avoid the code-base being VS Code dependent, i.e. by shipping with EV's in launch.json as the method for managing secrets.

**Comment by dstaudt** [comment]
This should be fixed by recent-ish changes, closing
